name 'chefazure-ch06'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chefazure-ch06'
long_description 'Installs/Configures chefazure-ch06'
version '0.1.0'
