name 'chefazure-ch01'
maintainer 'Stuart Preston'
maintainer_email 'stuart@pendrica.com'
license 'all_rights'
description 'Installs/Configures chefazure-ch01'
long_description 'Installs/Configures chefazure-ch01'
version '0.1.0'
