name 'provision'
maintainer 'Stuart Preston'
maintainer_email 'stuart@pendrica.com'
license 'all_rights'
description 'Installs/Configures provision'
long_description 'Installs/Configures provision'
version '0.1.0'
